# NAME
name: Build and Deploy ASP .NET Core Chapter 12 to GitHub Pages

# TRIGGER
on:
  # trigger the workflow only when a push happens in Chapter 12, koden nedan
  push:
    branches: [ master ]
    paths:
    - 'Chapter 12/Chapter_12_GitHubActions_Examples/**'

# BUILD
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
    - name: Publish app
        run: dotnet publish -c Release './Chapter12/Chapter_12_GitHubActions_Examples/Chapter12.csproj'
    - name: Save artifacts
        uses: actions/upload-artifacts@v2
        with: 
            name: myWASM
            path: './Chapter12/Chapter_12_GitHubActions_Examples/bin/Release/net5.0/publish/wwwroot/'

# DEPLOY
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create pages branch
        continue-on-error: true
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "tokareg@hotmail.com"
            git checkout -B pages
    - name: Clear pages branch
        continue-on-error: true
        run: |
            git rm -rf .
            git commit --allow-empty -m "root commit"
            git push -f origin pages
    - name: Download build artifact
        uses: actions/download-artifacts@v2
        with:
            name: myWASM
    - name: Commit changes
        run |
            git add .
            git commit -m "publishing WASM"
            git push --set-upstream origin pages
